server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: http://localhost:8081/
          predicates:
            - Path=/admin-service/**
        - id: openstack-service
          uri: http://localhost:8082/
          predicates:
            - Path=/openstack-service/**
        - id: user-service
          uri: http://localhost:8083/
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>.*), /$\{segment}
            - JwtAuthenticationFilter

jwt:
  secret: cloudclubsecretkey123cloudclubsecretkey123cloudclubsecretkey123cloudclubsecretkey123

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include:
          refresh, health, beans, busrefresh
